// <auto-generated />
namespace MVC_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TB_M_User1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TB_M_User1));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271255092_TB_M_User1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
